Repository moyeothon/F4_Front, pull requests merged in 2024-11, with the labels that each got.

#5 [Feat/#4] 팀 생성 페이지 구현
  src/Router.tsx
  src/components/create/TeamButton.tsx
  src/components/create/style.ts
  src/components/hintText/HintText1.tsx
  src/pages/create/Create.tsx
  src/pages/login/Login.tsx
Labels: 은혜, ✨ Feature, 🎨 Design

#7 [Feat/#6] 팀원 초대 페이지 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/components/common/button/Button.tsx
  src/components/common/hintText/HintText1.tsx
  src/components/common/hintText/HintText2.tsx
  src/components/common/input/DateInput.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/style.ts
  src/components/invite/profile/ActivatedProfile.tsx
  src/components/invite/profile/DeactivatedProfile.tsx
  src/components/invite/profile/style.ts
  src/components/invite/urlCopy/UrlCopy.tsx
  src/components/invite/urlCopy/style.ts
  src/pages/create/Create.tsx
  src/pages/invite/Invite.tsx
  src/pages/login/Login.tsx
Labels: 은혜, ✨ Feature, 🎨 Design

#8 [Feature] #2 - 테스트 페이지 UI 구현
  README.md
  build.sh
  index.html
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/instance.ts
  src/constants/testText.ts
  src/hooks/useUserProfile.ts
  src/pages/test/Test.tsx
  src/pages/test/_components/button/TestButton.tsx
  src/pages/test/_components/button/style.ts
  src/pages/test/_components/circle/CircleInfo.tsx
  src/pages/test/_components/circle/style.ts
  src/pages/test/_hooks/usePageNumber.ts
  src/pages/test/style.ts
  src/styles/global.ts
Labels: 세호, ✨ Feature, 🎨 Design

#19 [Feat/#10] 프로필 등록 페이지 구현
  src/Router.tsx
  src/components/common/button/Button.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/style.ts
  src/components/common/radio/Radio.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/personal/ImgInput.tsx
  src/pages/personal/Personal.tsx
Labels: 은혜, ✨ Feature, 🎨 Design

#22 [Style/#18] 온보딩 페이지 UI 구현
  src/Router.tsx
  src/assets/background.png
  src/components/common/button/Button.tsx
  src/pages/main/Main.tsx
  src/pages/main/style.ts
Labels: 은혜, 🎨 Design
